version: '3.9'
services:
  caddy:
    container_name: caddy
    image: caddy:2
#    network_mode: host
    ports:
      - "2019:2019"
      - "8080:80"
      - "8443:443"
    depends_on:
      - pds
    restart: unless-stopped
    volumes:
      - type: bind
        source: /share/Container/pds/caddy/data
        target: /data
      - type: bind
        source: /share/Container/pds/caddy/etc/caddy
        target: /etc/caddy
  pds:
    container_name: pds
    build:
      context: .
      dockerfile: Dockerfile
#    network_mode: host
    ports:
      - "2583:2583"
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /share/Container/pds
        target: /pds
    env_file:
      - /pds/pds.env
